apiVersion: apps/v1
kind:  Deployment
metadata:
  name: myapp-deployment
  labels:
    app: container110523
spec:
  replicas: 4
  selector:
    matchLabels:
      app: container110523
  template:
    metadata:
      name: myapp
      labels: 
        app: container110523
    spec:
      containers:
        - name: myapp
          image: container110523.azurecr.io/myapp:latest
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: container110523
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000
